name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    environment:
      name: firebase
      url: "https://workshop-2305.web.app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
    
      - name: Deploy to Firebase
        run: npm install -g firebase-tools@10.9.2
      - run: firebase deploy --only hosting:dev --site workshop-2305-dev --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}